CREATE TABLE IF NOT EXISTS pieces (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    grade TEXT NOT NULL,
    pic TEXT NOT NULL,
    value INTEGER NOT NULL,
    description TEXT NOT NULL
);