services:
  auth:
    build: ./auth
    ports:
      - 5001:5000
  # user:
    # build: ./user
    # ports:
      # - 5002:5000
  piece:
    build: ./piece
    ports:
      - 5003:5000
  banner:
    build: ./banner
    ports:
      - 5004:5000
  auction:
    build: ./auction
    ports:
      - 5005:5000