services:
  user_gateway:
    build: ./user_gateway
    ports:
      - "3000:80"
    networks:
      - user_network
    volumes:
      - ./user_gateway:/app
    depends_on:
      - auth
      - user
      #- piece
      #- banner
      - auction

  admin_gateway:
    build: ./admin_gateway
    ports:
      - "3001:80"
    networks:
      - admin_network
    volumes:
      - ./admin_gateway:/app
    depends_on:
      - auth
      - user
      #- piece
      #- banner
      #- auction

  auth:
    build: ./auth
    ports:
      - "3002:5000"
    networks:
      - admin_network
      - user_network
    volumes:
      - ./auth:/app
      - ./auth/data:/app/data

  user:
    build: ./user
    ports:
      - "5002:5000"
    networks:
      - admin_network
      - user_network
    volumes:
      - ./user:/app
      - ./user/data:/app/data

  piece:
    build: ./piece
    ports:
      - "5003:5000"
    networks:
      - admin_network
      - user_network
    secrets:
      - piece_cert_secret
      - piece_key_secret

  banner:
    build: ./banner
    ports:
      - "5004:5000"
    networks:
      - admin_network
      - user_network
    secrets:
      - banner_cert_secret
      - banner_key_secret

  auction:
    build: ./auction
    ports:
      - "5005:5000"
    networks:
      - admin_network
      - user_network

networks:
  admin_network:
    driver: bridge
  user_network:
    driver: bridge

secrets:
  piece_cert_secret:
    file: ./piece/cert.pem
  piece_key_secret:
    file: ./piece/key.pem
  banner_cert_secret:
    file: ./banner/cert.pem
  banner_key_secret:
    file: ./banner/key.pem