name: Postman Unit Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install Newman
      run: |
        npm install -g newman

    - name: Build and start Docker containers
      working-directory: ./server
      run: |
        # build and run
        docker compose -f docker-compose-unit-tests.yml up --build -d
        
        sleep 60
        
    - name: Run Auction Unit Tests
      run: |
        newman run ./docs/tests/unit_tests/Auction.Unit.Tests.postman_collection.json --insecure
        
    - name: Run Auth Unit Tests
      run: |
        newman run ./docs/tests/unit_tests/Auth.Unit.Tests.postman_collection.json --insecure
        
    - name: Run Banner Unit Tests
      run: |
        newman run ./docs/tests/unit_tests/Unit\ tests\ banner.postman_collection.json --insecure
        
    - name: Run Piece Unit Tests
      run: |
        newman run ./docs/tests/unit_tests/Unit\ tests\ piece.postman_collection.json --insecure
        
    - name: Run User Unit Tests
      run: |
        newman run ./docs/tests/unit_tests/User.Unit.Test.postman_collection.json --insecure
        
    - name: Stop Docker containers
      if: always()
      working-directory: ./server
      run: |
        docker compose -f docker-compose-unit-tests.yml down
        
    - name: Upload tests results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: newman-results
        path: newman/
