name: Postman Integration Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install Newman
      run: |
        npm install -g newman

    - name: Build and start Docker containers
      working-directory: ./server
      run: |
        # build and run
        docker compose -f docker-compose-tests.yml up --build -d
        
        sleep 60
        
    - name: Run User Auth Auction Integration Tests
      run: |
        newman run ./docs/tests/integration_tests/User.Auth.Auction.postman_collection.json --insecure

    - name: Run Piece Integration Tests
      run: |
        newman run ./docs/tests/integration_tests/Integration tests piece.postman_collection.json --insecure

    - name: Run Banner Integration Tests
      run: |
        newman run ./docs/tests/integration_tests/Integration tests banner.postman_collection.json --insecure
        
    - name: Stop Docker containers
      if: always()
      working-directory: ./server
      run: |
        docker compose -f docker-compose-tests.yml down -v
        
    - name: Upload tests results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: newman-results
        path: newman/
